# Generated by Django 5.1.6 on 2025-02-15 19:37

import django.db.models.deletion
import leagues.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default=leagues.models.default_round_name, max_length=200)),
                ('par', models.IntegerField(default=54)),
                ('payout', models.IntegerField(default=0)),
                ('complete', models.BooleanField(default=False)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.league')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
